apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-latest-kustomization-app-1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/agarhwal-deqode/argocd-kustomization.git
    targetRevision: HEAD
    path: environments/production
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-argocd-kustomization-app-1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
